rvm:
  - 2.6.3
  - ruby-head
gemfile:
  - gemfiles/Gemfile.rails-3.x
  - gemfiles/Gemfile.rails-4.x
  - Gemfile
notifications:
  recipients:
    - jarmo@jarmopertman.com
matrix:
  allow_failures:
    - rvm: ruby-head
