rvm:
 - 2.2.0
 - 2.1.5- 
 - 2.0.0
 - ruby-head
gemfile:
  - gemfiles/Gemfile.rails-2.x
  - gemfiles/Gemfile.rails-3.x
  - Gemfile
notifications:
  recipients:
    - jarmo.p@gmail.com
matrix:
  allow_failures:
    - rvm: ruby-head

